export {
  selectActiveMenuId,
  selectFocusedWindow,
  selectFocusedWindowId,
  selectSelectedIconId,
  selectSessionCurrentNav,
  selectSessionNavDepth,
  selectWindowById,
  selectWindowCount,
  selectWindowsByZ,
  selectWindowsInOrder,
  type WindowingStateSlice,
} from './selectors';
export type {
  CardSessionRef,
  DesktopState,
  NavEntry,
  OpenWindowPayload,
  SessionNav,
  WindowBounds,
  WindowContent,
  WindowContentKind,
  WindowInstance,
  WindowingState,
} from './types';
export {
  clearDesktopTransient,
  closeWindow,
  focusWindow,
  moveWindow,
  openWindow,
  resizeWindow,
  sessionNavBack,
  sessionNavGo,
  sessionNavHome,
  setActiveMenu,
  setSelectedIcon,
  windowingReducer,
} from './windowingSlice';
