export {
  selectActiveMenuId,
  selectDesktopContextMenu,
  selectFocusedWindow,
  selectFocusedWindowId,
  selectSelectedIconId,
  selectSessionCurrentNav,
  selectSessionNavDepth,
  selectWindowById,
  selectWindowCount,
  selectWindowsByZ,
  selectWindowsInOrder,
  type WindowingStateSlice,
} from './selectors';
export type {
  RuntimeSurfaceSessionRef,
  DesktopContextMenuActionItem,
  DesktopContextMenuIconKind,
  DesktopContextMenuItem,
  DesktopContextMenuSeparator,
  DesktopContextMenuState,
  DesktopContextMenuTarget,
  DesktopContextMenuTargetKind,
  DesktopState,
  NavEntry,
  OpenWindowPayload,
  SessionNav,
  WindowBounds,
  WindowContent,
  WindowContentKind,
  WindowInstance,
  WindowingState,
} from './types';
export {
  clearDesktopTransient,
  closeDesktopContextMenu,
  closeWindow,
  focusWindow,
  moveWindow,
  openWindow,
  resizeWindow,
  sessionNavBack,
  sessionNavGo,
  sessionNavHome,
  setDesktopContextMenu,
  setActiveMenu,
  setSelectedIcon,
  windowingReducer,
} from './windowingSlice';
