import type { Game } from './types';

export const SAMPLE_GAMES: Game[] = [
  {
    id: 'g1',
    title: 'Dark Castle',
    genre: 'Action',
    year: '1986',
    dev: 'Silicon Beach Software',
    size: '800K',
    rating: 4,
    installed: true,
    hours: 42.5,
    lastPlayed: 'Feb 28, 1991',
    art: 'castle',
    desc: 'Navigate through a treacherous castle filled with bats, rats, and the sinister Black Knight. Throw rocks, dodge fireballs, and survive 14 deadly levels.',
    achievements: [
      { name: 'First Blood', desc: 'Defeat your first enemy', done: true, icon: '\u2694\uFE0F' },
      { name: 'Black Knight Down', desc: 'Defeat the Black Knight', done: true, icon: '\uD83C\uDFF4' },
      { name: 'No Death Run', desc: 'Complete the game without dying', done: false, icon: '\uD83D\uDC80' },
      { name: 'Speed Demon', desc: 'Complete in under 20 minutes', done: false, icon: '\u23F1\uFE0F' },
    ],
  },
  {
    id: 'g2',
    title: 'Bolo',
    genre: 'Strategy',
    year: '1987',
    dev: 'Stuart Cheshire',
    size: '256K',
    rating: 5,
    installed: true,
    hours: 128.3,
    lastPlayed: 'Mar 1, 1991',
    art: 'tank',
    desc: 'Command a tank in this networked multiplayer strategy game. Build walls, lay mines, capture pillboxes, and destroy enemy bases over AppleTalk.',
    achievements: [
      { name: 'First Capture', desc: 'Capture your first pillbox', done: true, icon: '\uD83C\uDFC1' },
      { name: 'Engineer', desc: 'Build 50 walls', done: true, icon: '\uD83E\uDDF1' },
      { name: 'Demolitions Expert', desc: 'Destroy 100 enemy walls', done: true, icon: '\uD83D\uDCA3' },
      { name: 'Undefeated', desc: 'Win 10 games in a row', done: false, icon: '\uD83C\uDFC6' },
    ],
  },
  {
    id: 'g3',
    title: 'Glider PRO',
    genre: 'Puzzle',
    year: '1991',
    dev: 'Casady & Greene',
    size: '512K',
    rating: 4,
    installed: true,
    hours: 67.1,
    lastPlayed: 'Feb 25, 1991',
    art: 'glider',
    desc: 'Pilot a paper airplane through rooms of a haunted house. Ride air vents, dodge obstacles, and collect stars in this physics-based adventure.',
    achievements: [
      { name: 'Takeoff', desc: 'Complete the first room', done: true, icon: '\u2708\uFE0F' },
      { name: 'Star Collector', desc: 'Collect 100 stars', done: true, icon: '\u2B50' },
      { name: 'Full House', desc: 'Complete all rooms', done: false, icon: '\uD83C\uDFE0' },
      { name: 'Perfectionist', desc: 'Get every star in one run', done: false, icon: '\uD83D\uDC8E' },
    ],
  },
  {
    id: 'g4',
    title: 'Crystal Quest',
    genre: 'Arcade',
    year: '1987',
    dev: 'Patrick Buckland',
    size: '384K',
    rating: 5,
    installed: true,
    hours: 89.7,
    lastPlayed: 'Feb 27, 1991',
    art: 'crystal',
    desc: 'Collect crystals while dodging and shooting swarms of enemies in an arena. Features progressive difficulty across increasingly chaotic waves.',
    achievements: [
      { name: 'Crystal Clear', desc: 'Clear your first wave', done: true, icon: '\uD83D\uDC8E' },
      { name: 'Sharpshooter', desc: '95% accuracy in a wave', done: true, icon: '\uD83C\uDFAF' },
      { name: 'Wave 50', desc: 'Reach wave 50', done: false, icon: '\uD83C\uDF0A' },
      { name: 'Million Points', desc: 'Score 1,000,000 points', done: false, icon: '\uD83D\uDD22' },
    ],
  },
  {
    id: 'g5',
    title: 'Shufflepuck Cafe',
    genre: 'Sports',
    year: '1989',
    dev: 'Br\u00F8derbund',
    size: '640K',
    rating: 3,
    installed: false,
    hours: 15.2,
    lastPlayed: 'Jan 12, 1991',
    art: 'puck',
    desc: 'Air hockey at a seedy intergalactic cafe. Challenge 9 alien opponents with unique playing styles, from the easy-going Skip to the unbeatable Bejin.',
    achievements: [
      { name: 'Regular', desc: 'Beat your first opponent', done: true, icon: '\uD83C\uDFD2' },
      { name: 'Barfly', desc: 'Beat 5 opponents', done: true, icon: '\uD83C\uDF7A' },
      { name: 'Champion', desc: 'Beat all 9 opponents', done: false, icon: '\uD83D\uDC51' },
      { name: 'Perfect Game', desc: 'Win 15-0', done: false, icon: '\u2728' },
    ],
  },
  {
    id: 'g6',
    title: 'Prince of Persia',
    genre: 'Platformer',
    year: '1989',
    dev: 'Br\u00F8derbund',
    size: '768K',
    rating: 5,
    installed: false,
    hours: 0,
    lastPlayed: 'Never',
    art: 'prince',
    desc: 'You have 60 minutes to escape the dungeon, defeat Jaffar, and rescue the Princess. Run, jump, and swordfight through deadly traps and guards.',
    achievements: [
      { name: 'Escapee', desc: 'Escape the first level', done: false, icon: '\uD83D\uDD13' },
      { name: 'Swordsman', desc: 'Win your first duel', done: false, icon: '\uD83D\uDDE1\uFE0F' },
      { name: 'Jaffar Slayer', desc: 'Defeat Jaffar', done: false, icon: '\uD83D\uDC73' },
      { name: 'Speed Prince', desc: 'Finish in under 30 minutes', done: false, icon: '\uD83D\uDC51' },
    ],
  },
  {
    id: 'g7',
    title: 'Lode Runner',
    genre: 'Puzzle',
    year: '1983',
    dev: 'Br\u00F8derbund',
    size: '128K',
    rating: 4,
    installed: true,
    hours: 55.0,
    lastPlayed: 'Feb 20, 1991',
    art: 'loderunner',
    desc: 'Collect all the gold while evading guards. Dig holes to trap enemies and navigate 150 increasingly complex levels. Includes a level editor.',
    achievements: [
      { name: 'Gold Digger', desc: 'Complete 10 levels', done: true, icon: '\uD83E\uDE99' },
      { name: 'Architect', desc: 'Create a custom level', done: true, icon: '\uD83D\uDCD0' },
      { name: 'Master Runner', desc: 'Complete all 150 levels', done: false, icon: '\uD83C\uDFC3' },
      { name: 'Trap Master', desc: 'Trap 5 guards at once', done: false, icon: '\uD83D\uDD73\uFE0F' },
    ],
  },
  {
    id: 'g8',
    title: 'SimCity',
    genre: 'Simulation',
    year: '1989',
    dev: 'Maxis',
    size: '1.2MB',
    rating: 5,
    installed: true,
    hours: 203.8,
    lastPlayed: 'Mar 1, 1991',
    art: 'simcity',
    desc: 'Build and manage your own city. Zone residential, commercial, and industrial areas. Manage budgets, disasters, and keep your citizens happy.',
    achievements: [
      { name: 'Founder', desc: 'Reach 2,000 population', done: true, icon: '\uD83C\uDFD8\uFE0F' },
      { name: 'Mayor', desc: 'Reach 10,000 population', done: true, icon: '\uD83C\uDFD9\uFE0F' },
      { name: 'Megalopolis', desc: 'Reach 500,000 population', done: true, icon: '\uD83C\uDF06' },
      { name: 'Disaster Master', desc: 'Survive all disasters', done: false, icon: '\uD83C\uDF2A\uFE0F' },
    ],
  },
];
