export const PARTS = {
  // Widget root
  root: 'hypercard',
  // Primitives
  btn: 'btn',
  chip: 'chip',
  toast: 'toast',
  // Window chrome
  windowFrame: 'window-frame',
  titleBar: 'title-bar',
  closeBox: 'close-box',
  titleText: 'title-text',
  tabBar: 'tab-bar',
  tab: 'tab',
  // Navigation
  navBar: 'nav-bar',
  // Data display
  dataTable: 'data-table',
  tableHeader: 'table-header',
  tableRow: 'table-row',
  tableCell: 'table-cell',
  tableEmpty: 'table-empty',
  tableFooter: 'table-footer',
  // Cards
  card: 'card',
  cardTitle: 'card-title',
  cardBody: 'card-body',
  cardToolbar: 'card-toolbar',
  // Menu
  menuGrid: 'menu-grid',
  // Fields
  fieldGrid: 'field-grid',
  fieldLabel: 'field-label',
  fieldValue: 'field-value',
  fieldInput: 'field-input',
  formView: 'form-view',
  detailView: 'detail-view',
  // Buttons
  buttonGroup: 'button-group',
  // Filter
  filterBar: 'filter-bar',
  // Status
  statusBar: 'status-bar',
  // Report
  reportView: 'report-view',
  reportRow: 'report-row',
  // Chat
  chatView: 'chat-view',
  chatTimeline: 'chat-timeline',
  chatMessage: 'chat-message',
  chatComposer: 'chat-composer',
  chatInput: 'chat-input',
  chatSuggestions: 'chat-suggestions',
  // AI panel
  aiPanel: 'ai-panel',
  aiPanelHeader: 'ai-panel-header',
  // Desktop windowing shell
  windowingDesktopShell: 'windowing-desktop-shell',
  windowingMenuBar: 'windowing-menu-bar',
  windowingMenuButton: 'windowing-menu-button',
  windowingMenuPanel: 'windowing-menu-panel',
  windowingMenuItem: 'windowing-menu-item',
  windowingMenuShortcut: 'windowing-menu-shortcut',
  windowingMenuSeparator: 'windowing-menu-separator',
  windowingIconLayer: 'windowing-icon-layer',
  windowingIcon: 'windowing-icon',
  windowingIconGlyph: 'windowing-icon-glyph',
  windowingIconLabel: 'windowing-icon-label',
  windowingWindowLayer: 'windowing-window-layer',
  windowingWindow: 'windowing-window',
  windowingWindowTitleBar: 'windowing-window-title-bar',
  windowingCloseButton: 'windowing-close-button',
  windowingWindowTitle: 'windowing-window-title',
  windowingWindowBody: 'windowing-window-body',
  windowingResizeHandle: 'windowing-resize-handle',
  // macOS-style form controls
  checkbox: 'checkbox',
  checkboxMark: 'checkbox-mark',
  radioButton: 'radio-button',
  radioButtonDot: 'radio-button-dot',
  // ListBox
  listBox: 'list-box',
  listBoxItem: 'list-box-item',
  // DropdownMenu
  dropdownMenu: 'dropdown-menu',
  dropdownMenuTrigger: 'dropdown-menu-trigger',
  dropdownMenuPanel: 'dropdown-menu-panel',
  dropdownMenuItem: 'dropdown-menu-item',
  // ContextMenu
  contextMenu: 'context-menu',
  contextMenuItem: 'context-menu-item',
  contextMenuSeparator: 'context-menu-separator',
  // AlertDialog
  alertDialog: 'alert-dialog',
  alertDialogIcon: 'alert-dialog-icon',
  alertDialogMessage: 'alert-dialog-message',
  // ToolPalette
  toolPalette: 'tool-palette',
  toolPaletteItem: 'tool-palette-item',
  // ProgressBar
  progressBar: 'progress-bar',
  progressBarFill: 'progress-bar-fill',
  // TabControl
  tabControl: 'tab-control',
  // DisclosureTriangle
  disclosureTriangle: 'disclosure-triangle',
  disclosureTriangleArrow: 'disclosure-triangle-arrow',
  disclosureTriangleContent: 'disclosure-triangle-content',
  // HaloTarget
  haloTarget: 'halo-target',
  haloHandle: 'halo-handle',
  haloLabel: 'halo-label',
  haloBorder: 'halo-border',
} as const;

export type PartName = (typeof PARTS)[keyof typeof PARTS];
