export {
  selectActiveMenuId,
  selectActiveInteractionId,
  selectEffectiveWindowBoundsById,
  selectFocusedWindow,
  selectFocusedWindowId,
  selectInteractionDraftById,
  selectSelectedIconId,
  selectSessionCurrentNav,
  selectSessionNavDepth,
  selectWindowById,
  selectWindowCount,
  selectWindowsByZ,
  selectWindowsInOrder,
  type WindowingStateSlice,
} from './selectors';
export type {
  CardSessionRef,
  DesktopState,
  NavEntry,
  OpenWindowPayload,
  SessionNav,
  WindowBounds,
  WindowContent,
  WindowContentKind,
  WindowInteractionMode,
  WindowInteractionState,
  WindowInstance,
  WindowingState,
} from './types';
export {
  beginWindowInteraction,
  cancelWindowInteraction,
  clearWindowInteraction,
  clearDesktopTransient,
  closeWindow,
  commitWindowInteraction,
  focusWindow,
  moveWindow,
  openWindow,
  resizeWindow,
  sessionNavBack,
  sessionNavGo,
  sessionNavHome,
  setActiveMenu,
  setSelectedIcon,
  updateWindowInteractionDraft,
  windowingReducer,
} from './windowingSlice';
