import type { Stream, ChatMessage } from './types';

export const STREAMS: Stream[] = [
  {
    id: 's1',
    title: 'HyperCard Dev Stream',
    host: 'Bill Atkinson',
    cat: '\u{1F5A5}\uFE0F Tech',
    viewers: 2847,
    status: 'live',
    desc: 'Building interactive stacks with HyperTalk scripting',
    duration: '2:34:12',
    thumb: 'hypercard',
  },
  {
    id: 's2',
    title: 'ResEdit Workshop',
    host: 'Resourceful Mac',
    cat: '\u{1F5A5}\uFE0F Tech',
    viewers: 1203,
    status: 'live',
    desc: 'Custom icons and dialog resources for System 7',
    duration: '1:12:05',
    thumb: 'resedit',
  },
  {
    id: 's3',
    title: 'Marathon Speedrun',
    host: 'BungieFan_91',
    cat: '\uD83C\uDFAE Gaming',
    viewers: 5621,
    status: 'live',
    desc: "Any% glitchless WR attempt \u2014 Pfhor gonna get it",
    duration: '0:45:33',
    thumb: 'marathon',
  },
  {
    id: 's4',
    title: 'Dark Castle Challenge',
    host: 'RetroPixel',
    cat: '\uD83C\uDFAE Gaming',
    viewers: 892,
    status: 'live',
    desc: 'No-death run through all 14 levels',
    duration: '0:22:10',
    thumb: 'darkcastle',
  },
  {
    id: 's5',
    title: 'Ambient Mac Sounds',
    host: 'LoFi Finder',
    cat: '\uD83C\uDFB5 Music',
    viewers: 12450,
    status: 'live',
    desc: 'System sounds, floppy drives & keyboard ASMR to study to',
    duration: '8:15:00',
    thumb: 'lofi',
  },
  {
    id: 's6',
    title: 'MIDI Jam Session',
    host: 'SynthWoz',
    cat: '\uD83C\uDFB5 Music',
    viewers: 634,
    status: 'live',
    desc: 'Live composing on a IIgs with MIDI interface',
    duration: '1:55:20',
    thumb: 'midi',
  },
  {
    id: 's7',
    title: 'Pixel Art in MacPaint',
    host: 'Susan K.',
    cat: '\uD83C\uDFA8 Creative',
    viewers: 3210,
    status: 'live',
    desc: 'Designing icons in 32x32 black & white',
    duration: '3:01:44',
    thumb: 'macpaint',
  },
  {
    id: 's8',
    title: 'PageMaker Layout',
    host: 'DesktopPub',
    cat: '\uD83C\uDFA8 Creative',
    viewers: 445,
    status: 'offline',
    desc: 'Designing a zine layout with Aldus PageMaker 4.0',
    duration: '\u2014',
    thumb: 'pagemaker',
  },
  {
    id: 's9',
    title: 'AppleTalk LAN Party',
    host: 'NetTalk',
    cat: '\uD83D\uDCE1 Live',
    viewers: 1876,
    status: 'live',
    desc: '8-player Bolo tournament over LocalTalk',
    duration: '0:58:17',
    thumb: 'lan',
  },
  {
    id: 's10',
    title: "Macworld '91 Keynote",
    host: 'Apple Archive',
    cat: '\uD83D\uDCFC Archive',
    viewers: 789,
    status: 'vod',
    desc: 'Classic keynote \u2014 System 7 announcement replay',
    duration: '1:32:00',
    thumb: 'keynote',
  },
  {
    id: 's11',
    title: 'Inside Macintosh Read',
    host: 'BookWorm',
    cat: '\uD83D\uDCFC Archive',
    viewers: 156,
    status: 'vod',
    desc: 'Reading through Volume I, chapter by chapter',
    duration: '4:10:30',
    thumb: 'insdemac',
  },
  {
    id: 's12',
    title: 'Photoshop 1.0 Tutorial',
    host: 'PixelPerfect',
    cat: '\uD83C\uDFA8 Creative',
    viewers: 2100,
    status: 'vod',
    desc: 'Photo retouching on a Quadra 700',
    duration: '0:48:15',
    thumb: 'photoshop',
  },
];

export const CHAT_MESSAGES: ChatMessage[] = [
  { user: 'MacFan84', msg: 'This is incredible \u{1F5A5}\uFE0F' },
  { user: 'PixelPushr', msg: 'can you zoom in on that?' },
  { user: 'RetroGeek', msg: 'I remember using this!' },
  { user: 'SystemSeven', msg: 'Classic. Pure classic.' },
  { user: 'WozIsMyHero', msg: 'the good old days' },
  { user: 'DesktopPub', msg: 'what resolution is that?' },
  { user: 'PowerUser', msg: 'try Command-Shift-3' },
  { user: 'HyperNerd', msg: 'amazing stream today' },
];
