// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sem/hypercard/widget.proto

package hypercardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WidgetLifecycleV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	WidgetType    string                 `protobuf:"bytes,3,opt,name=widget_type,json=widgetType,proto3" json:"widget_type,omitempty"`
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetLifecycleV1) Reset() {
	*x = WidgetLifecycleV1{}
	mi := &file_sem_hypercard_widget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetLifecycleV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetLifecycleV1) ProtoMessage() {}

func (x *WidgetLifecycleV1) ProtoReflect() protoreflect.Message {
	mi := &file_sem_hypercard_widget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetLifecycleV1.ProtoReflect.Descriptor instead.
func (*WidgetLifecycleV1) Descriptor() ([]byte, []int) {
	return file_sem_hypercard_widget_proto_rawDescGZIP(), []int{0}
}

func (x *WidgetLifecycleV1) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *WidgetLifecycleV1) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WidgetLifecycleV1) GetWidgetType() string {
	if x != nil {
		return x.WidgetType
	}
	return ""
}

func (x *WidgetLifecycleV1) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *WidgetLifecycleV1) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WidgetLifecycleV1) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_sem_hypercard_widget_proto protoreflect.FileDescriptor

const file_sem_hypercard_widget_proto_rawDesc = "" +
	"\n" +
	"\x1asem/hypercard/widget.proto\x12\rsem.hypercard\x1a\x1cgoogle/protobuf/struct.proto\"\xbc\x01\n" +
	"\x11WidgetLifecycleV1\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vwidget_type\x18\x03 \x01(\tR\n" +
	"widgetType\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04dataB`Z^github.com/go-go-golems/hypercard-inventory-chat/internal/pinoweb/pb/sem/hypercard;hypercardpbb\x06proto3"

var (
	file_sem_hypercard_widget_proto_rawDescOnce sync.Once
	file_sem_hypercard_widget_proto_rawDescData []byte
)

func file_sem_hypercard_widget_proto_rawDescGZIP() []byte {
	file_sem_hypercard_widget_proto_rawDescOnce.Do(func() {
		file_sem_hypercard_widget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sem_hypercard_widget_proto_rawDesc), len(file_sem_hypercard_widget_proto_rawDesc)))
	})
	return file_sem_hypercard_widget_proto_rawDescData
}

var file_sem_hypercard_widget_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sem_hypercard_widget_proto_goTypes = []any{
	(*WidgetLifecycleV1)(nil), // 0: sem.hypercard.WidgetLifecycleV1
	(*structpb.Struct)(nil),   // 1: google.protobuf.Struct
}
var file_sem_hypercard_widget_proto_depIdxs = []int32{
	1, // 0: sem.hypercard.WidgetLifecycleV1.data:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sem_hypercard_widget_proto_init() }
func file_sem_hypercard_widget_proto_init() {
	if File_sem_hypercard_widget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sem_hypercard_widget_proto_rawDesc), len(file_sem_hypercard_widget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sem_hypercard_widget_proto_goTypes,
		DependencyIndexes: file_sem_hypercard_widget_proto_depIdxs,
		MessageInfos:      file_sem_hypercard_widget_proto_msgTypes,
	}.Build()
	File_sem_hypercard_widget_proto = out.File
	file_sem_hypercard_widget_proto_goTypes = nil
	file_sem_hypercard_widget_proto_depIdxs = nil
}
