- type: local
  path: /home/manuel/Downloads/hypercard-dev-guide.md
  lastFetched: 2026-02-12T11:37:40.484271635-05:00
- type: local
  path: /home/manuel/Downloads/hypercard(4).jsx
  lastFetched: 2026-02-12T11:37:40.658709464-05:00
